name: Develop CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create dummy .env
        run: |
          echo "VITE_API_URL=https://dummy.api" > .env

      - name: Run build
        run: npm run build

      - name: Run lint (optional)
        run: npm run lint
        continue-on-error: true

      - name: Run unit tests (optional)
        run: npm run test
        continue-on-error: true
